// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXujLliP2ZxXFVylFFJLmP1Yk7ax3M724',
    appId: '1:480846989770:web:bea89c3f013c69c8a56733',
    messagingSenderId: '480846989770',
    projectId: 'goarrival',
    authDomain: 'goarrival.firebaseapp.com',
    storageBucket: 'goarrival.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD457k4nLJnpLO9GDPwMFuTZfiaqGdBrbk',
    appId: '1:480846989770:android:a80d4f0ce39f6159a56733',
    messagingSenderId: '480846989770',
    projectId: 'goarrival',
    storageBucket: 'goarrival.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJo6yNddOuarcuAdVWsZHKmVByqwTB86U',
    appId: '1:480846989770:ios:bd375eae0e8a376fa56733',
    messagingSenderId: '480846989770',
    projectId: 'goarrival',
    storageBucket: 'goarrival.firebasestorage.app',
    iosBundleId: 'com.example.goarrival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJo6yNddOuarcuAdVWsZHKmVByqwTB86U',
    appId: '1:480846989770:ios:bd375eae0e8a376fa56733',
    messagingSenderId: '480846989770',
    projectId: 'goarrival',
    storageBucket: 'goarrival.firebasestorage.app',
    iosBundleId: 'com.example.goarrival',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXujLliP2ZxXFVylFFJLmP1Yk7ax3M724',
    appId: '1:480846989770:web:302f02de739da6d8a56733',
    messagingSenderId: '480846989770',
    projectId: 'goarrival',
    authDomain: 'goarrival.firebaseapp.com',
    storageBucket: 'goarrival.firebasestorage.app',
  );

}