// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuAJdjiRSSQ2i8pko7MI2Sa4HYWrWZAU',
    appId: '1:240931923565:web:2e2eac5f05ca3a29fe4164',
    messagingSenderId: '240931923565',
    projectId: 'goarrival-jgrs',
    authDomain: 'goarrival-jgrs.firebaseapp.com',
    storageBucket: 'goarrival-jgrs.firebasestorage.app',
    measurementId: 'G-G7ZKT90HKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWQJzJjgSPngO73Hm-tR-daN9d6zyvoB4',
    appId: '1:240931923565:android:91c6bf6872a91499fe4164',
    messagingSenderId: '240931923565',
    projectId: 'goarrival-jgrs',
    storageBucket: 'goarrival-jgrs.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmuAJdjiRSSQ2i8pko7MI2Sa4HYWrWZAU',
    appId: '1:240931923565:web:c5cc906139b1fcfbfe4164',
    messagingSenderId: '240931923565',
    projectId: 'goarrival-jgrs',
    authDomain: 'goarrival-jgrs.firebaseapp.com',
    storageBucket: 'goarrival-jgrs.firebasestorage.app',
    measurementId: 'G-7JPHPRE9WH',
  );
}
